### ISSUE TITLE
HadoopNative fails to load SnappyCodec

### ISSUE THREAD

**Issue by kongul** [prestosql/presto-hadoop-apache#22]
Doing presto restarts, from time to time we're getting following issue on different nodes during initializing `hive` or `iceberg` connector.
We can't reproduce it, cause we have it once in 5 restarts or so.
We are started to get it after migration to jdk11 and Presto version 343 (previously we used 326)

```2020-10-23T11:24:25.833Z	ERROR	main	io.prestosql.server.Server	null
java.lang.ExceptionInInitializerError
	at io.prestosql.plugin.hive.HdfsEnvironment$$FastClassByGuice$$2c8553d4.newInstance(<generated>)
	at com.google.inject.internal.DefaultConstructionProxyFactory$FastClassProxy.newInstance(DefaultConstructionProxyFactory.java:89)
	at com.google.inject.internal.ConstructorInjector.provision(ConstructorInjector.java:114)
	at com.google.inject.internal.ConstructorInjector.access$000(ConstructorInjector.java:32)
	at com.google.inject.internal.ConstructorInjector$1.call(ConstructorInjector.java:98)
	at com.google.inject.internal.ProvisionListenerStackCallback$Provision.provision(ProvisionListenerStackCallback.java:112)
	at io.airlift.bootstrap.LifeCycleModule.provision(LifeCycleModule.java:54)
	at com.google.inject.internal.ProvisionListenerStackCallback$Provision.provision(ProvisionListenerStackCallback.java:120)
	at com.google.inject.internal.ProvisionListenerStackCallback.provision(ProvisionListenerStackCallback.java:66)
	at com.google.inject.internal.ConstructorInjector.construct(ConstructorInjector.java:93)
	at com.google.inject.internal.ConstructorBindingImpl$Factory.get(ConstructorBindingImpl.java:306)
	at com.google.inject.internal.ProviderToInternalFactoryAdapter.get(ProviderToInternalFactoryAdapter.java:40)
	at com.google.inject.internal.SingletonScope$1.get(SingletonScope.java:168)
	at com.google.inject.internal.InternalFactoryToProviderAdapter.get(InternalFactoryToProviderAdapter.java:39)
	at com.google.inject.internal.SingleParameterInjector.inject(SingleParameterInjector.java:42)
	at com.google.inject.internal.SingleParameterInjector.getAll(SingleParameterInjector.java:65)
	at com.google.inject.internal.ConstructorInjector.provision(ConstructorInjector.java:113)
	at com.google.inject.internal.ConstructorInjector.access$000(ConstructorInjector.java:32)
	at com.google.inject.internal.ConstructorInjector$1.call(ConstructorInjector.java:98)
	at com.google.inject.internal.ProvisionListenerStackCallback$Provision.provision(ProvisionListenerStackCallback.java:112)
	at io.airlift.bootstrap.LifeCycleModule.provision(LifeCycleModule.java:54)
	at com.google.inject.internal.ProvisionListenerStackCallback$Provision.provision(ProvisionListenerStackCallback.java:120)
	at com.google.inject.internal.ProvisionListenerStackCallback.provision(ProvisionListenerStackCallback.java:66)
	at com.google.inject.internal.ConstructorInjector.construct(ConstructorInjector.java:93)
	at com.google.inject.internal.ConstructorBindingImpl$Factory.get(ConstructorBindingImpl.java:306)
	at com.google.inject.internal.FactoryProxy.get(FactoryProxy.java:62)
	at com.google.inject.internal.ProviderToInternalFactoryAdapter.get(ProviderToInternalFactoryAdapter.java:40)
	at com.google.inject.internal.SingletonScope$1.get(SingletonScope.java:168)
	at com.google.inject.internal.InternalFactoryToProviderAdapter.get(InternalFactoryToProviderAdapter.java:39)
	at com.google.inject.internal.InternalInjectorCreator.loadEagerSingletons(InternalInjectorCreator.java:213)
	at com.google.inject.internal.InternalInjectorCreator.injectDynamically(InternalInjectorCreator.java:184)
	at com.google.inject.internal.InternalInjectorCreator.build(InternalInjectorCreator.java:111)
	at com.google.inject.Guice.createInjector(Guice.java:87)
	at io.airlift.bootstrap.Bootstrap.initialize(Bootstrap.java:276)
	at io.prestosql.plugin.iceberg.InternalIcebergConnectorFactory.createConnector(InternalIcebergConnectorFactory.java:83)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at io.prestosql.plugin.iceberg.IcebergConnectorFactory.create(IcebergConnectorFactory.java:42)
	at io.prestosql.connector.ConnectorManager.createConnector(ConnectorManager.java:353)
	at io.prestosql.connector.ConnectorManager.createCatalog(ConnectorManager.java:212)
	at io.prestosql.connector.ConnectorManager.createCatalog(ConnectorManager.java:204)
	at io.prestosql.connector.ConnectorManager.createCatalog(ConnectorManager.java:190)
	at io.prestosql.metadata.StaticCatalogStore.loadCatalog(StaticCatalogStore.java:88)
	at io.prestosql.metadata.StaticCatalogStore.loadCatalogs(StaticCatalogStore.java:68)
	at io.prestosql.server.Server.doStart(Server.java:119)
	at io.prestosql.server.Server.lambda$start$0(Server.java:73)
	at io.prestosql.$gen.Presto_344____20201023_112418_1.run(Unknown Source)
	at io.prestosql.server.Server.start(Server.java:73)
	at io.prestosql.server.PrestoServer.main(PrestoServer.java:38)
Caused by: java.lang.RuntimeException: failed to load Hadoop native library
	at io.prestosql.hadoop.HadoopNative.requireHadoopNative(HadoopNative.java:59)
	at io.prestosql.plugin.hive.HdfsEnvironment.<clinit>(HdfsEnvironment.java:39)
	... 51 more
Caused by: java.lang.RuntimeException: native snappy library not available: SnappyCompressor has not been loaded.
	at org.apache.hadoop.io.compress.SnappyCodec.checkNativeCodeLoaded(SnappyCodec.java:72)
	at org.apache.hadoop.io.compress.SnappyCodec.getDecompressorType(SnappyCodec.java:195)
	at io.prestosql.hadoop.HadoopNative.loadAllCodecs(HadoopNative.java:72)
	at io.prestosql.hadoop.HadoopNative.requireHadoopNative(HadoopNative.java:53)
	... 52 more```

**Comment by phd3** [comment]
> native snappy library not available: SnappyCompressor has not been loaded.

@kongul One possible reason behind this can be that an incorrect version of snappy is being picked up from a configured `java.library.path` attribute value (as opposed to the one being packaged with presto). It may help
to make sure that nothing is being provided in this parameter (through tools like jinfo). 

relevant slack discussion: https://prestosql.slack.com/archives/CFLB9AMBN/p1597806230063000

**Comment by phd3** [comment]
Feel free to reach out on [Slack](https://prestosql.io/slack.html) to discuss this further! Closing this issue.

**Comment by kongul** [comment]
Thank you! Removed `java.library.path` ant it works just fine!
